
services:
  chroma-server:
    image: chromadb/chroma:latest
    container_name: skripsi_chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db_storage:/data
    restart: always

  api-skripsi:
    build: .
    container_name: skripsi_backend
    command: uvicorn src.main_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
      # Konfigurasi koneksi Client-Server ke ChromaDB
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    depends_on:
      - chroma-server

    restart: always

  db-viewer:
    build: .
    container_name: skripsi_viewer
    command: streamlit run src/view_database.py --server.port 8501 --server.runOnSave true
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./src:/app/src
    depends_on:
      - api-skripsi
      - chroma-server
    environment:
      - PYTHONUNBUFFERED=1
      # URL diubah murni ke endpoint /search (Information Retrieval / Semantic Search)
      - API_URL=http://api-skripsi:8000/search
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    restart: always