version: '3.8'

services:
  chroma-server:
    image: chromadb/chroma:latest
    container_name: skripsi_chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db_storage:/data
    restart: always

  api-skripsi:
    build: .
    container_name: skripsi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./output:/app/output
      # HAPUS: - ./chroma_db_storage:/app/chroma_db_storage (karena sudah diurus chroma-server)
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./eksperimen:/app/eksperimen
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama-service:11434
      - RAG_LLM_BACKEND=ollama
      - RAG_MODEL_NAME=gemma2:2b
      # TAMBAHKAN: Konfigurasi host dan port untuk nyambung ke Chroma
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    depends_on:
      - ollama-service
      - chroma-server # Pastikan chroma nyala duluan
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

  db-viewer:
    build: .
    container_name: skripsi_viewer
    command: streamlit run src/view_database.py --server.port 8501 --server.runOnSave true
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./src:/app/src
    depends_on:
      - api-skripsi
      - chroma-server
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://api-skripsi:8000/rag/ask
      - OLLAMA_HOST=http://ollama-service:11434
      - RAG_LLM_BACKEND=ollama
      - RAG_MODEL_NAME=gemma2:2b
      # TAMBAHKAN: Konfigurasi host dan port
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-service:
    image: ollama/ollama:latest
    container_name: skripsi_ollama
    ports:
      - "11434:11434"
    volumes:
      - D:\LLM:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always